### ISSUE TITLE
Travis Builds are now Failing from circuitpython-build-bundles

### ISSUE THREAD

**Issue by makermelissa** [adafruit/circuitpython-build-tools#34]
Here's the error in Travis
```
$ circuitpython-build-bundles --filename_prefix adafruit-circuitpython-featherwing --library_location .
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/bin/circuitpython-build-bundles", line 11, in <module>
    sys.exit(build_bundles())
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
TypeError: build_bundles() got an unexpected keyword argument 'package_folder_prefix'
The command "circuitpython-build-bundles --filename_prefix adafruit-circuitpython-featherwing --library_location ." exited with 1.
```

**Comment by makermelissa** [comment]
Fixed by #33
