### ISSUE TITLE
Building mpy-cross 2.31 and fails

### ISSUE THREAD

**Issue by mpechner** [adafruit/circuitpython-build-tools#43]
I followed the instructions to build Adafruit_CircuitPython_Register.
Ran circuitpython-build-bundles --filename_prefix adafruit-circuitpython-register --library_location . 
And the build failed when circuitpython-build-bundles tried to  build mpy-cross.

(circuitpython) Mikeys-MBP:Adafruit_CircuitPython_Register mpechner$ circuitpython-build-bundles --filename_prefix adafruit-circuitpython-register --library_location .
Deleting existing build.

Generating VERSIONS

Zipping
adafruit-circuitpython-register-py-1.7.1/examples/register_rwbits.py 1218 1536
adafruit-circuitpython-register-py-1.7.1/examples/register_rwbit.py 1232 1536
adafruit-circuitpython-register-py-1.7.1/examples/register_unarystruct.py 1288 1536
adafruit-circuitpython-register-py-1.7.1/examples/register_struct.py 1062 1536
adafruit-circuitpython-register-py-1.7.1/lib/adafruit_register/i2c_bit.py 3469 3584
adafruit-circuitpython-register-py-1.7.1/lib/adafruit_register/i2c_struct_array.py 4785 5120
adafruit-circuitpython-register-py-1.7.1/lib/adafruit_register/i2c_bcd_datetime.py 4337 4608
adafruit-circuitpython-register-py-1.7.1/lib/adafruit_register/i2c_bcd_alarm.py 7290 7680
adafruit-circuitpython-register-py-1.7.1/lib/adafruit_register/init.py 0 0
adafruit-circuitpython-register-py-1.7.1/lib/adafruit_register/i2c_bits.py 4676 5120
adafruit-circuitpython-register-py-1.7.1/lib/adafruit_register/i2c_struct.py 4293 4608

37888 B 37.0 kiB 0.0361328125 MiB
Bundled in bundles/adafruit-circuitpython-register-py-1.7.1.zip

Building mpy-cross for circuitpython 2.3.1
M	mpy-cross/Makefile
M	mpy-cross/gccollect.c
M	mpy-cross/main.c
M	mpy-cross/mpconfigport.h
M	mpy-cross/mphalport.h
HEAD is now at 6e95c9040 Merge pull request #812 from dhalbert/2.x-filesystem-writability-on-boot
Use make V=1, make V=2 or set BUILD_VERBOSE similarly in your environment to increase build verbosity.
rm -f mpy-cross
rm -f mpy-cross.map
rm -rf build
Use make V=1, make V=2 or set BUILD_VERBOSE similarly in your environment to increase build verbosity.
Generating build/genhdr/mpversion.h
GEN build/genhdr/qstr.i.last
QSTR updated
GEN build/genhdr/qstrdefs.generated.h
main.c:200:25: error: no member named 'native_arch' in 'struct mp_dynamic_compiler_t'
mp_dynamic_compiler.native_arch = MP_NATIVE_ARCH_X64;
~~~~~~~~~~~~~~~~~~~ ^
main.c:200:39: error: use of undeclared identifier 'MP_NATIVE_ARCH_X64'
mp_dynamic_compiler.native_arch = MP_NATIVE_ARCH_X64;
^
main.c:260:41: error: no member named 'native_arch' in 'struct mp_dynamic_compiler_t'
mp_dynamic_compiler.native_arch = MP_NATIVE_ARCH_X86;
~~~~~~~~~~~~~~~~~~~ ^
main.c:260:55: error: use of undeclared identifier 'MP_NATIVE_ARCH_X86'
mp_dynamic_compiler.native_arch = MP_NATIVE_ARCH_X86;
^
main.c:262:41: error: no member named 'native_arch' in 'struct mp_dynamic_compiler_t'
mp_dynamic_compiler.native_arch = MP_NATIVE_ARCH_X64;
~~~~~~~~~~~~~~~~~~~ ^
main.c:262:55: error: use of undeclared identifier 'MP_NATIVE_ARCH_X64'
mp_dynamic_compiler.native_arch = MP_NATIVE_ARCH_X64;
^
main.c:264:41: error: no member named 'native_arch' in 'struct mp_dynamic_compiler_t'
mp_dynamic_compiler.native_arch = MP_NATIVE_ARCH_ARMV6;
~~~~~~~~~~~~~~~~~~~ ^
main.c:264:55: error: use of undeclared identifier 'MP_NATIVE_ARCH_ARMV6'
mp_dynamic_compiler.native_arch = MP_NATIVE_ARCH_ARMV6;
^
main.c:266:41: error: no member named 'native_arch' in 'struct mp_dynamic_compiler_t'
mp_dynamic_compiler.native_arch = MP_NATIVE_ARCH_ARMV7M;
~~~~~~~~~~~~~~~~~~~ ^
main.c:266:55: error: use of undeclared identifier 'MP_NATIVE_ARCH_ARMV7M'
mp_dynamic_compiler.native_arch = MP_NATIVE_ARCH_ARMV7M;
^
main.c:268:41: error: no member named 'native_arch' in 'struct mp_dynamic_compiler_t'
mp_dynamic_compiler.native_arch = MP_NATIVE_ARCH_XTENSA;
~~~~~~~~~~~~~~~~~~~ ^
main.c:268:55: error: use of undeclared identifier 'MP_NATIVE_ARCH_XTENSA'
mp_dynamic_compiler.native_arch = MP_NATIVE_ARCH_XTENSA;
^
12 errors generated.
make: *** [build/main.o] Error 1
Traceback (most recent call last):
File "/Users/mpechner/dev/circuitpython/bin/circuitpython-build-bundles", line 11, in 
load_entry_point('circuitpython-build-tools==1.2.6', 'console_scripts', 'circuitpython-build-bundles')()
File "/Users/mpechner/dev/circuitpython/lib/python3.7/site-packages/click/core.py", line 764, in call
return self.main(*args, **kwargs)
File "/Users/mpechner/dev/circuitpython/lib/python3.7/site-packages/click/core.py", line 717, in main
rv = self.invoke(ctx)
File "/Users/mpechner/dev/circuitpython/lib/python3.7/site-packages/click/core.py", line 956, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/Users/mpechner/dev/circuitpython/lib/python3.7/site-packages/click/core.py", line 555, in invoke
return callback(*args, **kwargs)
File "/Users/mpechner/dev/circuitpython/lib/python3.7/site-packages/circuitpython_build_tools/scripts/build_bundles.py", line 173, in build_bundles
build.mpy_cross(mpy_cross, version["tag"])
File "/Users/mpechner/dev/circuitpython/lib/python3.7/site-packages/circuitpython_build_tools/build.py", line 85, in mpy_cross
shutil.copy("build_deps/circuitpython/mpy-cross/mpy-cross", mpy_cross_filename)
File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py", line 241, in copy
copyfile(src, dst, follow_symlinks=follow_symlinks)
File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py", line 120, in copyfile
with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'build_deps/circuitpython/mpy-cross/mpy-cross'
(circuitpython) Mikeys-MBP:Adafruit_CircuitPython_Register mpechner$ ls -l build_deps/circuitpython/mpy-cross/mpy


circuitpython-build-tools builds a copy of mp-cross.
Look in: https://github.com/adafruit/circuitpython-build-https://github.com/adafruit/circuitpython-build-tools/blob/master/circuitpython_build_tools/scripts/build_mpy_cross.py

if name == "main":
output_directory = sys.argv[1]
os.makedirs(output_directory, exist_ok=True)
for version in target_versions.VERSIONS:
mpy_cross = output_directory + "/mpy-cross-" + version["name"]
build.mpy_cross(mpy_cross, version["tag"])

then:
https://github.com/adafruit/circuitpython-build-tools/blob/master/circuitpython_build_tools/target_versions.py
VERSIONS = [
{"tag": "2.3.1", "name": "2.x"},
{"tag": "3.0.0", "name": "3.x"},
{"tag": "4.0.0-alpha.2", "name": "4.x"},
]

So the last checkin for target_versions.py re-added version 2.31. Th is is why you see the errors.

**Comment by jtrip** [comment]
I think I am experiencing a similar issue, trying to build **Adafruit_CircuitPython_Display_Text** .   

looking at the `.env/lib/python3.5/site-packages/circuitpython_build_tools/target_versions.py` I found the versions mentioned above.  

To try and understand I removed the 2.3.1 entry dict from that list and ran the build again. It then correctly skips that version and succeeds at building the 3.0.0 version but then fails on the 4.0.0 version similarly. It fails to find the `build_deps/circuitpython/mpy-cross/mpy-cross`, presumably because building that failed. It seems like we would want some 4.x version to succeed at least, the fact that it shows 4.0.0-alpha.2 also seems odd considering 4.0.0 was released May 20th. So it looks like these target versions are not what we want them to be maybe.

Do these target versions just need to updated by whomever is building?  
What are the successful build target requirements for changes made to these libraries?  

```
Building mpy-cross for circuitpython 4.0.0-alpha.2
==================================================
M	tools/uf2
Previous HEAD position was 85a5276f3 Merge pull request #1006 from dhalbert/3.x-fix-pull
HEAD is now at b24fdcab3 Merge pull request #1278 from dhalbert/update-frozen-for-alpha.2
Submodule path 'tools/uf2': checked out '968716efd30600984139d706bcbd8ec1a1b2336d'
Submodule 'tools/huffman' (https://github.com/tannewt/huffman.git) registered for path 'huffman'
Cloning into '/Users/jtrip/Projects/circuitpython/Adafruit_CircuitPython_Display_Text/build_deps/circuitpython/tools/huffman'...
Submodule path 'huffman': checked out '27b1bba76198a0b343f694a6d680b5293d1c56aa'
Use make V=1, make V=2 or set BUILD_VERBOSE similarly in your environment to increase build verbosity.
rm -f mpy-cross
rm -f mpy-cross.map
rm -rf build
Use make V=1, make V=2 or set BUILD_VERBOSE similarly in your environment to increase build verbosity.
QSTR updated
python3 ../py/makeqstrdata.py build/genhdr/qstrdefs.preprocessed.h > build/genhdr/qstrdefs.enum.h
make: msgfmt: No such file or directory
make: *** [build/genhdr/en_US.mo] Error 1
Traceback (most recent call last):
  File "/Users/jtrip/Projects/circuitpython/Adafruit_CircuitPython_Display_Text/.env/bin/circuitpython-build-bundles", line 10, in <module>
    sys.exit(build_bundles())
  File "/Users/jtrip/Projects/circuitpython/Adafruit_CircuitPython_Display_Text/.env/lib/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jtrip/Projects/circuitpython/Adafruit_CircuitPython_Display_Text/.env/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/jtrip/Projects/circuitpython/Adafruit_CircuitPython_Display_Text/.env/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jtrip/Projects/circuitpython/Adafruit_CircuitPython_Display_Text/.env/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/jtrip/Projects/circuitpython/Adafruit_CircuitPython_Display_Text/.env/lib/python3.5/site-packages/circuitpython_build_tools/scripts/build_bundles.py", line 173, in build_bundles
    build.mpy_cross(mpy_cross, version["tag"])
  File "/Users/jtrip/Projects/circuitpython/Adafruit_CircuitPython_Display_Text/.env/lib/python3.5/site-packages/circuitpython_build_tools/build.py", line 85, in mpy_cross
    shutil.copy("build_deps/circuitpython/mpy-cross/mpy-cross", mpy_cross_filename)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'build_deps/circuitpython/mpy-cross/mpy-cross'
```

**Comment by jtrip** [comment]
Ok I made some progress, so I might be good to move on but there are some remaining concerns.  

I noticed (in the output above) the line `make: msgfmt: No such file or directory` and that seemed actionable. So after some investigation I found that this tool should be provided by the **gettext** package, which may or may not be already present for some users. So on my mac, `brew install gettext` let me know I already had it and I may need to update it. So I ran `brew upgrade gettext` which worked but trying to run `msgfmt` still failed and I discovered that homebrew was not linking it properly. Running `brew link gettext --force`  resolves that and then I was able to run msgfmt from bash as a test as expected.   

In the meantime I also updated my target version entry for 4.x to point to the **4.0.2** tag.  

With this, the most recent non-beta non-rc release, and a fixed gettext setup...  

`circuitpython-build-bundles --filename_prefix adafruit-circuitpython-display_text --library_location .`
works!  

After that success I figured I'd go back and try the other versions that the tool has set by default (including 2.x entry) ... However using the 2.3.1 tag still fails for some other reason I haven't dove into yet. BTW, The failing build attempt is on an unmodified version of the library of course,  `commit 1dd413de602d617337d5dbafe5ea059eba143ddb`

So I still would like some clarity on why those target_versions are listed by default and how developers should choose to update those, is testing builds for 2.x still required for a pull request to be accepted? etc.

**Comment by ladyada** [comment]
hiya you just need mpy cross right?

**Comment by jtrip** [comment]
Hi @ladyada , yeah for the 2.3.1 target it looks like it is failing because it can't find mpy-cross.  

```
../py/nlrx64.c:44:9: error: macro expansion producing 'defined' has undefined behavior [-Werror,-Wexpansion-to-defined]
    #if NLR_OS_WINDOWS
        ^
../py/nlrx64.c:37:25: note: expanded from macro 'NLR_OS_WINDOWS'
#define NLR_OS_WINDOWS (defined(_WIN32) || defined(__CYGWIN__))
                        ^
../py/nlrx64.c:44:9: error: macro expansion producing 'defined' has undefined behavior [-Werror,-Wexpansion-to-defined]
../py/nlrx64.c:37:44: note: expanded from macro 'NLR_OS_WINDOWS'
#define NLR_OS_WINDOWS (defined(_WIN32) || defined(__CYGWIN__))
                                           ^
../py/nlrx64.c:112:9: error: macro expansion producing 'defined' has undefined behavior [-Werror,-Wexpansion-to-defined]
    #if NLR_OS_WINDOWS
        ^
../py/nlrx64.c:37:25: note: expanded from macro 'NLR_OS_WINDOWS'
#define NLR_OS_WINDOWS (defined(_WIN32) || defined(__CYGWIN__))
                        ^
../py/nlrx64.c:112:9: error: macro expansion producing 'defined' has undefined behavior [-Werror,-Wexpansion-to-defined]
../py/nlrx64.c:37:44: note: expanded from macro 'NLR_OS_WINDOWS'
#define NLR_OS_WINDOWS (defined(_WIN32) || defined(__CYGWIN__))
                                           ^
4 errors generated.
make: *** [build/py/nlrx64.o] Error 1
Traceback (most recent call last):
  File "/Users/jtrip/Projects/circuitpython/Adafruit_CircuitPython_Display_Text/.env/bin/circuitpython-build-bundles", line 10, in <module>
    sys.exit(build_bundles())
  File "/Users/jtrip/Projects/circuitpython/Adafruit_CircuitPython_Display_Text/.env/lib/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jtrip/Projects/circuitpython/Adafruit_CircuitPython_Display_Text/.env/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/jtrip/Projects/circuitpython/Adafruit_CircuitPython_Display_Text/.env/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jtrip/Projects/circuitpython/Adafruit_CircuitPython_Display_Text/.env/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/jtrip/Projects/circuitpython/Adafruit_CircuitPython_Display_Text/.env/lib/python3.5/site-packages/circuitpython_build_tools/scripts/build_bundles.py", line 173, in build_bundles
    build.mpy_cross(mpy_cross, version["tag"])
  File "/Users/jtrip/Projects/circuitpython/Adafruit_CircuitPython_Display_Text/.env/lib/python3.5/site-packages/circuitpython_build_tools/build.py", line 85, in mpy_cross
    shutil.copy("build_deps/circuitpython/mpy-cross/mpy-cross", mpy_cross_filename)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'build_deps/circuitpython/mpy-cross/mpy-cross'
```

**Comment by ladyada** [comment]
here's mpycross for v3/v4 (what we support now
https://learn.adafruit.com/creating-and-sharing-a-circuitpython-library/creating-a-library#mpy-2-11
you can get mpycross v2 here, but we're kinda moved on from v2
https://github.com/adafruit/circuitpython/releases/tag/2.3.0

**Comment by jtrip** [comment]
Oh cool, that's great, I didn't see that guide before.  

I was primarily concerned about using the **circuitpython-build-tools** to build after making changes to a library and it seemed to me that process needs to dynamically load spy-cross for the given target_versions.  

Glad to hear we are leaving the past behind!

**Comment by tannewt** [comment]
Closing this. You shouldn't need to build libraries with mpy-cross manually. In general, just use the .py file on the device.
