### ISSUE TITLE
Investigate Odd Travis-based Traceback Messages

### ISSUE THREAD

**Issue by sommersoft** [adafruit/circuitpython-build-tools#51]
A couple users on Discord have reported some strange behavior with exception Tracebacks:
```
Traceback (most recent call last):
  File "code.py", line 1169, in <module>
  File "code.py", line 259, in load_font
  File "code.py", line 248, in load_font
  File "/home/travis/build/adafruit/Adafruit_CircuitPython_Bundle/libraries/helpers/bitmap-font/adafruit_bitmap_font/bitmap_font.py", line 51, in load_font
OSError: [Errno 2] No such file/directory
```
The strangeness being the `File "/home/travis/build/..."`.

I suspect this is stemming from an issue during [`_munge_to_temp`](https://github.com/adafruit/circuitpython-build-tools/blob/master/circuitpython_build_tools/build.py#L93).

Maybe `__file__`, `__name__`, or the like is getting replaced somehow.

Users reported that this occured with `.mpy` files.

Thanks to anecdata and devoh for pointing this out.

**Comment by sommersoft** [comment]
Its getting into the `.mpy` somehow...
![all_your_mpys_belong_to_travis](https://user-images.githubusercontent.com/21211479/66782798-284db180-ee9c-11e9-8f41-4a07a68ae13b.png)

**Comment by sommersoft** [comment]
Pretty sure i found it. I was misunderstanding the [`-s`](https://github.com/adafruit/circuitpython/blob/master/mpy-cross/main.c#L104) argument for mpy-cross. Its not the source file, but rather the name to put in the bytecoded file as a filename. 

Should have a fix in for this soon. Just need to work out the proper truncation for [these](https://github.com/adafruit/circuitpython-build-tools/blob/master/circuitpython_build_tools/build.py#L179).
